# Generated by Django 6.0.5 on 2026-05-09 08:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('HOD', 'HOD'), ('Employee', 'Employee')], default='Employee', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('view_own_data', 'Can view own data'), ('edit_own_data', 'Can edit own data'), ('view_department_data', 'Can view department data'), ('edit_department_data', 'Can edit department data'), ('view_all_data', 'Can view all data'), ('edit_all_data', 'Can edit all data'), ('edit_own_credentials', 'Can edit own credentials'), ('edit_own_formalities', 'Can edit own formalities')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='Unknown Department', max_length=255)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Head of Department')),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tasks.department'),
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=255)),
                ('initial_employment_date', models.DateField()),
                ('last_date_of_employment', models.DateField()),
                ('current_position', models.CharField(max_length=255)),
                ('decision_time', models.CharField(choices=[('6-9 months ago', '6-9 months ago'), ('3-5 months ago', '3-5 months ago'), ('1-2 months ago', '1-2 months ago'), ('Less than a month', 'Less than a month')], max_length=20)),
                ('decision_time_comments', models.TextField(blank=True, null=True)),
                ('reasons', models.CharField(choices=[('Salary', 'Salary'), ('Family Responsibilities', 'Family Responsibilities'), ('Job Advancement', 'Job Advancement'), ('Dissatisfied/Management', 'Dissatisfied/Management'), ('Personal', 'Personal'), ('Benefits', 'Benefits'), ('Return to last company', 'Return to last company'), ('Job Eliminated', 'Job Eliminated'), ('Relocation', 'Relocation'), ('Quality of work', 'Quality of work'), ('Health issue', 'Health issue'), ('Other', 'Other')], max_length=50)),
                ('reason_comments', models.TextField(blank=True, null=True)),
                ('specific_event', models.BooleanField(default=False)),
                ('event_issue_comments', models.TextField(blank=True, null=True)),
                ('discuss_supervisor', models.BooleanField(default=False)),
                ('discuss_supervisor_comments', models.TextField(blank=True, null=True)),
                ('training_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('training_quality_comments', models.TextField(blank=True, null=True)),
                ('supervisor_relationship', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('supervisor_relationship_comments', models.TextField(blank=True, null=True)),
                ('employee_relationship', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('employee_relationship_comments', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('salary_comments', models.TextField(blank=True, null=True)),
                ('workload', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('satisfaction', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('satisfaction_comments', models.TextField(blank=True, null=True)),
                ('problems', models.BooleanField(default=False)),
                ('problems_comments', models.TextField(blank=True, null=True)),
                ('enjoy_most', models.TextField(blank=True, null=True)),
                ('enjoy_least', models.TextField(blank=True, null=True)),
                ('recommend', models.BooleanField(default=False)),
                ('recommend_comments', models.TextField(blank=True, null=True)),
                ('reapply', models.BooleanField(default=False)),
                ('reapply_comments', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('interviewer_name', models.CharField(max_length=255)),
                ('interview_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit Interview',
                'verbose_name_plural': 'Exit Interviews',
                'ordering': ['-interview_date_time'],
            },
        ),
        migrations.CreateModel(
            name='ExitProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('pending_clearance', 'Pending Clearance'), ('cleared', 'Cleared'), ('closed', 'Closed')], default='initiated', max_length=20)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_process', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_exits', to=settings.AUTH_USER_MODEL, verbose_name='Initiated by (HR)')),
            ],
            options={
                'verbose_name': 'Exit Process',
                'verbose_name_plural': 'Exit Processes',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_detail', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.department')),
            ],
            options={
                'ordering': ['department', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Employee Offboarding Task',
                'verbose_name_plural': 'Employee Offboarding Tasks',
                'ordering': ['task__department', 'task__pk'],
                'unique_together': {('employee', 'task')},
            },
        ),
    ]
