# Generated by Django 5.2.14 on 2026-05-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="employeetask",
            options={
                "ordering": [
                    "task__task_type",
                    "task__department__department_name",
                    "task__pk",
                ],
                "verbose_name": "Employee Offboarding Task",
                "verbose_name_plural": "Employee Offboarding Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["task_type", "department__department_name", "pk"]},
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (all employees, managed by HR)"),
                    ("departmental", "Departmental (managed by dept HOD)"),
                ],
                default="departmental",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="exitprocess",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("cleared", "Cleared"),
                    ("closed", "Closed"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for departmental tasks. Leave blank for standard tasks.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.department",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("EXIT_INITIATED", "Exit Initiated"),
                            ("EXIT_STATUS_CHANGED", "Exit Status Changed"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("INTERVIEW_SUBMITTED", "Interview Submitted"),
                            ("PROCESS_CLOSED", "Process Closed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
